name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: list files in word-ladder-solver
        run: ls word-ladder-solver

      - name: Install dependencies, build, and test
        run: |
          cd word-ladder-solver
          npm install
          npm run build
          npm run test
